
import React from 'react';
import {Affix} from 'antd';
class MobileTopic extends React.Component {
    constructor(props) {
        super(props);
    }
    render() {
        return (
            <div>
                <Affix>
                    <h1>hello world</h1>
                </Affix>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
                <p>fdf</p>
            </div>
        )
    }
}
export default  MobileTopic 